spring:
  data:
    cassandra:
      keyspace-name: taco_cloud
      schema-action: recreate
      local-datacenter: datacenter-1
#      contact-points:
#      - casshost-1: tacocloud.com
#      - casshost-2: tacocloud.com
#      - casshost-3: tacocloud.com
#      port: 9043
  datasource:
    name: TacoCloud
    generate-unique-name: false
    url: "jdbc:h2:mem:tacocloud"
  main:
    allow-bean-definition-overriding: true
