#server:
#  port: 8443
#  ssl:
#    key-store: file:///Users/shakil/Downloads/TacoCloud/mykeys.jks
#    key-store-password: password
#    key-password: password

spring:
  data:
    rest:
      base-path: /data-api
  datasource:
    name: TacoCloud
    generate-unique-name: false
    url: "jdbc:h2:mem:tacocloud"
  main:
    allow-bean-definition-overriding: true

logging:
  file:
    path: /Users/shakil/Downloads/TacoCloud/
    file: TacoCloud.log
  level:
    root: INFO
    org.springframework.security: DEBUG

read:
  values: { y: 20, z: 30, page-size: 15 }